language: python

addons:
  apt:
    packages:
      - python-pip

sudo: true

cache:
  directories:
  - $TRAVIS_BUILD_DIR/data/input

os: linux

compiler:
  - gcc

before_install:
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
  - cd /tmp && git clone -b development https://www.github.com/singularityware/singularity.git && cd singularity
  - sudo apt-get update && sudo apt-get install -y squashfs-tools
  - echo $PWD && ls
  - ./autogen.sh && ./configure --prefix=/usr/local && make && sudo make install
  - cd $TRAVIS_BUILD_DIR/

install:
  - sudo singularity build container.ftw Singularity

script:
  - singularity run -B data/input:/data/input -B $TRAVIS_BUILD_DIR/analysis:/code --pwd /code container.ftw
  - singularity exec -B data/input:/data/input -B $TRAVIS_BUILD_DIR/analysis:/code --pwd /code container.ftw python -m unittest discover -s /code/tests/ -p '[t|T]est*.py'

deploy:
  provider: surge
  project: ./results/
  domain: containers-ftw.surge.sh
